### ISSUE TITLE
文档写的总页码是 totalPage

### ISSUE THREAD

**Issue by hanxi** [jsososo/MiguMusicApi#1]
https://github.com/jsososo/MiguMusicApi/blob/1236a12c611f8ccdd719f525c49c6645d4f13465/routes/search.ts#L117

**Comment by jsososo** [comment]
嗯，是的，我过两天改一下，最近有点忙

**Comment by jsososo** [comment]
啊，今天抽空看了一下，发现是因为这个接口调整过，以前走的是网页爬虫，所以只能拿到 totalPage，现在走接口，拿到的是total 了，这里文档改了一下，就按 total 走了哈

**Comment by hanxi** [comment]
好的
