### ISSUE TITLE
{"result":400,"errMsg":"系统异常：read ECONNRESET"}

### ISSUE THREAD

**Issue by jiahui90** [jsososo/MiguMusicApi#11]
{"result":400,"errMsg":"系统异常：read ECONNRESET"}
报错了呀

**Comment by jsososo** [comment]
有挺多接口官方改掉了，后来都没啥时间看了😂

2020年11月14日 上午9:24，jiahui90 <notifications@github.com<mailto:notifications@github.com>> 写道：



{"result":400,"errMsg":"系统异常：read ECONNRESET"}
报错了呀
