### ISSUE TITLE
{"result":400,"errMsg":"系统异常：Unexpected end of JSON input"}

### ISSUE THREAD

**Issue by pood1e** [jsososo/MiguMusicApi#12]
出错了呀，{"result":400,"errMsg":"系统异常：Unexpected end of JSON input"}，看看什么问题哈
/search?keywords=xx

**Comment by pood1e** [comment]
> 出错了呀，{"result":400,"errMsg":"系统异常：Unexpected end of JSON input"}，看看什么问题哈

/search?keywords=xx

**Comment by jsososo** [comment]
官方修改接口了，我知道这个问题挺久了，但是一直没空，最近比较忙，可能下个星期会修吧

2020年11月29日 上午12:23，Pood1e <notifications@github.com<mailto:notifications@github.com>> 写道：



/search?keywords=xx
