### ISSUE TITLE
最新版已无法使用

### ISSUE THREAD

**Issue by k3sc** [jsososo/MiguMusicApi#19]
官网借口也无法使用 502

**Comment by jsososo** [comment]
官网演示接口已下线，因为这个不适合在服务器部署，会被ip封禁，本地部署是ok的

2021年6月17日 下午2:39，k ***@***.******@***.***>> 写道：



官网借口也无法使用 502

**Comment by k3sc** [comment]
![image](https://user-images.githubusercontent.com/28189393/122355350-66aa4680-cf84-11eb-90a2-d924adb64466.png)
![image](https://user-images.githubusercontent.com/28189393/122355376-6b6efa80-cf84-11eb-80dd-1b85180a0846.png)

**Comment by jsososo** [comment]
你在 util/request 里返回请求结果的地方打印一下看看，我本地同样搜索周杰伦是ok的

2021年6月17日 下午3:55，k ***@***.******@***.***>> 写道：



[image]<https://user-images.githubusercontent.com/28189393/122355350-66aa4680-cf84-11eb-90a2-d924adb64466.png>
[image]<https://user-images.githubusercontent.com/28189393/122355376-6b6efa80-cf84-11eb-80dd-1b85180a0846.png>
