### ISSUE TITLE
测试/song/url接口时加入needPic=1无法获取图片

### ISSUE THREAD

**Issue by zhengfan2014** [jsososo/MiguMusicApi#4]
http://api.migu.jsososo.com/song/url?id=3790007&cid=60054701923&needPic=1
返回：
`{"result":100,"data":{"128k":"http://tyst.migu.cn/public/product5th/product34/2019/07/1822/2009年06月26日博尔普斯/标清高清/MP3_128_16_Stero/60054701923.mp3","320k":"http://tyst.migu.cn/public/product5th/product34/2019/07/1822/2009年06月26日博尔普斯/标清高清/MP3_320_16_Stero/60054701923.mp3","flac":"http://tyst.migu.cn/public/ringmaker01/n17/2017/07/无损/2009年06月26日博尔普斯/flac/晴天-周杰伦.flac"}}`

**Comment by jsososo** [comment]
接口已重构
