### ISSUE TITLE
本地部署获取播放地址失败

### ISSUE THREAD

**Issue by xiaou520** [jsososo/MiguMusicApi#5]
大佬您好
![image](https://user-images.githubusercontent.com/63086611/81782133-f254d680-952b-11ea-9477-dbc65e482d10.png)
![image](https://user-images.githubusercontent.com/63086611/81782183-01d41f80-952c-11ea-9e17-31a4243340fe.png)
如果大佬有空可以给我一下解答吗，之前是可以的

**Comment by jsososo** [comment]
不好，我看了一下，好像我这儿也获取失败了，可能官方调过接口了。

**Comment by xiaou520** [comment]
太感谢了，

**Comment by jsososo** [comment]
只能说，我尽快看看吧，虽然是个比较严重的问题，但是migu 现在地位在这些项目里地位还比较低下，如果能帮忙解决也是再感谢不过

**Comment by xiaou520** [comment]
可以听就可以了刚刚发现可以获取低音质的

**Comment by xiaou520** [comment]
已经有办法解决了`https://app.c.nf.migu.cn/MIGUM2.0/v2.0/content/listen-url?netType=01&resourceType=E&songId=1002240937&toneFlag=SQ`
toneFlag 可以取LQ|PQ|HQ|SQ|ZQ
headers:
channel:0146951
uid:用户id

**Comment by jsososo** [comment]
Emmm，这个现在也要用户id了嘛，还真是头大。

**Comment by xiaou520** [comment]
不是userid 是uuid 之前没有测试完
