### ISSUE TITLE
{"result":200,"errMsg":"用户不存在, 1610000002:用户不存在"}

### ISSUE THREAD

**Issue by huachun168** [jsososo/MiguMusicApi#8]
有些歌曲并不能返回结果，
例如：1113136606

**Comment by jsososo** [comment]
这个是哪个接口触发的？

2020年8月1日 下午5:33，huachun168 <notifications@github.com<mailto:notifications@github.com>> 写道：



有些歌曲并不能返回结果，

**Comment by huachun168** [comment]
song?id=1113136606 @jsososo

**Comment by jsososo** [comment]
接口已重构 `/song?cid=1113136606`
